name: backend
env:
- name: DB_NAME
  secret:
    name: backend
    key: DB_NAME
- name: DB_HOST
  secret:
    name: backend
    key: DB_HOST
- name: DB_PORT
  secret:
    name: backend
    key: DB_PORT
- name: DB_PASSWORD
  secret:
    name: backend
    key: DB_PASSWORD
- name: DB_USER
  secret:
    name: backend
    key: DB_USER
- name: JWT_SECRET
  secret:
    name: backend
    key: JWT_SECRET
- name: NODE_ENV
  value: staging
- name: SLACK_URL
  secret:
    name: backend
    key: SLACK_URL
- name: STRIPE_API_KEY
  secret:
    name: backend
    key: STRIPE_API_KEY
processes:
  api:
    health:
      path: /health
      grace: 30
      interval: 3
      timeout: 1
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      host: pokedextracker.com
      path: /api(/|$)(.*)
    image:
      repo: pokedextracker/api.pokedextracker.com
    ports:
    - port: 8647
      public: true
      health: true
    resources:
      requests:
        memory: 128Mi
        cpu: 20m
      limits:
        memory: 512Mi
        cpu: 256m
