name: backend
env:
- name: DB_NAME
  secret:
    name: backend
    key: db_name
- name: DB_HOST
  secret:
    name: backend
    key: db_host
- name: DB_PORT
  secret:
    name: backend
    key: db_port
- name: DB_PASSWORD
  secret:
    name: backend
    key: db_password
- name: DB_USER
  secret:
    name: backend
    key: db_user
- name: JWT_SECRET
  secret:
    name: backend
    key: jwt_secret
- name: NODE_ENV
  value: production
- name: SLACK_URL
  secret:
    name: backend
    key: slack_url
- name: STRIPE_API_KEY
  secret:
    name: backend
    key: stripe_api_key
health:
  path: /health
  grace: 30
host: api.pokedextracker.com
image:
  repo: pokedextracker/api.pokedextracker.com
port: 8647
public: true
resources:
  requests:
    memory: 128Mi
    cpu: 20m
  limits:
    memory: 512Mi
    cpu: 256m
