name: backend
env:
- name: DATABASE_NAME
  secret:
    name: backend
    key: DB_NAME
- name: DATABASE_HOST
  secret:
    name: backend
    key: DB_HOST
- name: DATABASE_PASSWORD
  secret:
    name: backend
    key: DB_PASSWORD
- name: DATABASE_SSL_MODE
  value: disable
- name: DATABASE_USER
  secret:
    name: backend
    key: DB_USER
- name: ENVIRONMENT
  value: production
- name: JWT_SECRET
  secret:
    name: backend
    key: JWT_SECRET
- name: ROLLBAR_TOKEN
  secret:
    name: backend
    key: ROLLBAR_TOKEN
- name: STRIPE_API_KEY
  secret:
    name: backend
    key: STRIPE_API_KEY
processes:
  api:
    health:
      path: /health
      grace: 2
      interval: 3
      timeout: 1
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      host: pokedextracker.com
      path: /api(/|$)(.*)
    image:
      repo: pokedextracker/api.pokedextracker.com
    ports:
    - port: 8647
      public: true
      health: true
    resources:
      requests:
        memory: 128Mi
        cpu: 20m
      limits:
        memory: 512Mi
        cpu: 256m
