version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.14.2
      - image: circleci/postgres:9.4.11
        environment:
          POSTGRES_USER: pokedex_tracker_admin
          POSTGRES_DB: pokedex_tracker
          POSTGRES_PASSWORD: ""
    working_directory: ~/api.pokedextracker.com
    steps:
      - restore_cache:
          keys:
            - source-v0-{{ .Branch }}-{{ .Revision }}
            - source-v0-{{ .Branch }}-
            - source-v0-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/api.pokedextracker.com/.git
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/api.pokedextracker.com/node_modules
            - ~/.cache/yarn
      - run:
          name: Migrate database
          command: yarn db:migrate
      - run:
          name: Run linter
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Enforce coverage
          command: yarn enforce
      - run:
          name: Compress coverage directory
          command: test -d coverage && tar czvf ~/coverage.tar.gz coverage
          when: on_fail
      - store_artifacts:
          path: ~/coverage.tar.gz
